### PR TITLE
new pictures, text, and button

### PR DESCRIPTION
**Pull request by mwernimont**
@jlucido2 Heres the pull request for the added images, text, and learn more buttons.  A ton of the pull request I didn't touch but maybe its a weird R thing? I am not sure so thats why I am not merging it myself to avoid possible complications

### CODE REVIEW

**Comment by jordansread** [comment]
@jlucido2 what is the timeline on this? Need it reviewed quick?

**Comment by jlucido2** [comment]
@jread-usgs I'd like to get these changes pushed out by the end of the week if possible and if they are ready. Thanks

**Comment by jordansread** [comment]
there are 22,000 new lines of code added 
image
I will do my best.

**Comment by jlucido2** [comment]
Wow...I think that is one of the concerns. Marty isn't sure why github marked so many as changed. If it isn't reasonable this week I understand.

**Comment by lawinslow** [comment]
@mwernimont This PR has a huge number of line changes because you included the generated website with your commit. Could you get rid of index.html, index.md, and the index_files folder?

**Comment by mwernimont** [comment]
I will do my best!

**Comment by jlucido2** [comment]
@lawinslow - does it look better now?

**Comment by lawinslow** [comment]
Yup, much better!

**Pull request merged**
