### PR TITLE
Initial commit of code

### PR DESCRIPTION
**Pull request by lawinslow**
@jread-usgs this is pretty much ready for you. We need to figure out what we're doing with different depths of soil moisture data. See demo for how to grab sites and data.

### CODE REVIEW

**Comment by lawinslow** [comment]
@jlucido2, what parameter did they say they wanted us to use? It was SOIL MOISTURE PERCENT, right?

**Comment by jlucido2** [comment]
@lawinslow, looked at my notes. It says %current soil moisture.

**Comment by lawinslow** [comment]
Ok, good. Then I am using the correct parameter in the demo @jread-usgs

**Comment by jordansread** [comment]
@lawinslow you ready for me to try a map try?

**Comment by lawinslow** [comment]
Yup. Let me know if the demo or data aren't clear.

**Pull request merged**
